name: On Push Activity Box

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: JasonEtco/activity-box@master
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USERNAME: detailyang
          GIST_ID: 6d7c3e5244546f7854dc834b6f0fa98a
